### ISSUE TITLE
Should possibly create the tmpdir by means other than creating it in source

### ISSUE THREAD

**Issue by j-baker** [palantir/gradle-java-distribution#114]
Saw an internal product which forcibly deletes var/data before doing any docker tasks; this removed the tmpdir that gjd created. Gjd should consider creating the dir by some other mechanism, because the current method is liable to being tampered with and then leading to confusing runtime bugs.

**Comment by markelliot** [comment]
Yeah, we can do something different here.

**Comment by schlosna** [comment]
For Cassandra and ES you also need to set `jna.tmpdir` (similar to `java.io.tmpdir`), but might want them to be different, in which case you'd need to also create that a directory that is readable, writable, and executable (and isn't mounted with `noexec` as some `/tmp/` or `/var/tmp/` may be).

@tpetracca for SA 

https://docs.datastax.com/en/landing_page/doc/landing_page/troubleshooting/DSE/noWriteTmpDir.html and https://github.com/elastic/elasticsearch/issues/18272 for background

**Comment by quellkot** [comment]
It's not clear to me that gjd should create var/data and var/data/tmp at all?
If we do create them, then do we agree that they should always be empty?

(this was uschi2000/robert with a different account)

**Comment by schlosna** [comment]
Not sure what the state of SLS spec is, but I'd propose that GJD should create the minimum expected directory structure with appropriate permissioning, to include var/data/ and var/tmp/ (to be consistent with Linux filesystem hierarchy standards http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/var.html )

**Comment by uschi2000** [comment]
Hmm. I think it's generally safer to be explicit in your application: if you're expecting to write to var/data then you should make sure the directory exist and optionally create it if not. `var` is guaranteed to exist as per SLS.

**Comment by j-baker** [comment]
@uschi2000 you have to choose between either not setting java.io.tmpdir or making sure that the directory you set it to exists. Otherwise when any part of java tries to create a temporary file, it'll crash.

**Comment by quellkot** [comment]
Ah, yes I forgot about the tmpdir setting. Cool you're right.

**Comment by uschi2000** [comment]
fixed by #119
