### ISSUE TITLE
init.sh fails to check status correctly if service name is different than project name

### ISSUE THREAD

**Issue by saurabhshukla92** [palantir/gradle-java-distribution#115]
init.sh check tries to grep service name in the command for the PID. If the service name is different than project name, this check might fail with a generic failure message "process dead but PID exists". 

Three options I can think of to make this better:
(1) A better way to check command for the PID (not sure if there's another easy way)
(2) Enforce service name to be same as project name
(3) At minimum, fail with a better message, like "Could not find service name in command for PID"

**Comment by uschi2000** [comment]
I don't quite understand the problem. What do you mean by "service name is different than project name"?

**Comment by saurabhshukla92** [comment]
So PID command will have paths to jars etc in the project directory. If the service name is the same as the name of the project directory, grep for service name in the command will be fine. If the service name is different than project directory name, grep is unsuccessful (this was the failure case for me).
It's possible that service name appears in the command further down the line, but it is probably being truncated.

**Comment by uschi2000** [comment]
I see. It is assumed that the service is run from the unzipped directory. The grepping is done to verify that the service PID actually corresponds to the running service.
