### ISSUE TITLE
add option to print arbitrary message to stderr on start

### ISSUE THREAD

**Issue by jochs** [palantir/gradle-java-distribution#129]
I've seen several issues in the field whose root cause was people running `init.sh start` by hand instead of via lifecycle management tools. It would be nice to add an optional flag to the distribution block that would cause a message to be printed to stderr, so that when people do run the init script by hand they get immediate feedback telling them it may cause problems.

Something like `stdErrOnStart`, which takes the full message you want printed, maybe? I'm not sure if this is too specific.

**Comment by uschi2000** [comment]
How do you intend to detect "by hand" vs "by tool"?

**Comment by jochs** [comment]
I don't - things printed to stderr get ignored by the tool and wouldn't be surfaced.

**Comment by uschi2000** [comment]
OK.

**Comment by ash211** [comment]
Can you detect "by hand" vs "by tool" based on the environment variables set?  I don't know what the tool we're all talking about provides as environment.

**Comment by jochs** [comment]
I don't think you can rely on any env variables being set currently, but if/when we stop relying on puppet for bootstrapping that may be a possibility.

**Comment by Alexis-D** [comment]
Shouldn't you be able to check if `stdout` is a tty ([`isatty(3)`](http://man7.org/linux/man-pages/man3/isatty.3.html)), and behave differently if that's the case? Presumably if `stdout` is a tty, then the script is being ran manually, otherwise it's probably being ran as part of a script.
