### ISSUE TITLE
Change default GC settings

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-java-distribution#151]
cc @schlosna 

The JVM defaults are to use the Parallel Old GC collector.  Probably most services using g-j-d should be using either the CMS + Parallel New collector or the G1 collector.

Should we make an opinionated decision in g-j-d about a different default GC collector than the JVM defaults?

**Comment by schlosna** [comment]
I'm on the fence here -- it would be nice to provide the option to provide sets of GC config -- throughput (ParallelOld), response time (CMS+ParNew), hybrid (G1). G1 probably works for most workloads using g-j-d except if they embed Elasticsearch.

**Comment by schlosna** [comment]
I think it is probably worth allowing specification of `jvmGcOpts` that are configurable as a set, since we often want them applied atomically, and not overlapping with any other JVM args.
