### ISSUE TITLE
rotate GC logs?

### ISSUE THREAD

**Issue by bavardage** [palantir/gradle-java-distribution#152]

**Comment by gracew** [comment]
I'm not sure why these settings aren't working:
https://github.com/palantir/gradle-java-distribution/blob/develop/src/main/groovy/com/palantir/gradle/javadist/DistributionExtension.groovy#L22

since it corresponds to the information in http://stackoverflow.com/questions/3822097/rolling-garbage-collector-logs-in-java

however, I'm seeing 3000+ GC logs after upgrading from 0.9.0 to 1.0.0.

**Comment by uschi2000** [comment]
Can you verify that the options are passed to the `java` call correctly?

**Comment by gracew** [comment]
output of `jps -mv`

```
7810 StemmaServer server var/conf/stemma.yml -Djava.io.tmpdir=var/data/tmp -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:-TraceClassUnloading -XX:+UseGCLogFileRotation -XX:GCLogFileSize=10M -XX:NumberOfGCLogFiles=10 -Xloggc:var/log/gc-%t-%p.log -verbose:gc -Djavax.net.ssl.trustStore=/opt/palantir/services/.38590403/var/security/truststore.jks -Djavax.net.ssl.keyStore=/opt/palantir/services/.38590403/var/security/keystore.jks -Djavax.net.ssl.keyStorePassword=REDACTED -Xms4g -Xmx4g
```

**Comment by bavardage** [comment]
thought: not sure how log rotation interacts with parameters in the log file name

**Comment by bavardage** [comment]
the rfe is sorta vague http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6941923

**Comment by gracew** [comment]
@bavardage that's a good point, I'm pretty sure that's the cause of this. The filenames look like this:
```
-rw-r--r-- 1 palantir palantir  1561881 Nov 16 12:52 gc-2016-11-14_14-25-04-pid128525.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:27 gc-2016-11-14_14-27-23-pid697.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:28 gc-2016-11-14_14-28-23-pid1569.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:29 gc-2016-11-14_14-29-23-pid2487.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:30 gc-2016-11-14_14-30-23-pid3389.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:31 gc-2016-11-14_14-31-23-pid4205.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:32 gc-2016-11-14_14-32-23-pid5144.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:33 gc-2016-11-14_14-33-23-pid6459.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:34 gc-2016-11-14_14-34-23-pid7296.log.0.current
-rw-r--r-- 1 palantir palantir     1483 Nov 14 14:35 gc-2016-11-14_14-35-25-pid8191.log.0.current
```

If rolling worked correctly some of the suffixes should be "1", "2", etc.

**Comment by uschi2000** [comment]
Maybe useful? http://jesseyates.com/2012/11/05/rolling-java-gc-logs.html

**Comment by bavardage** [comment]
we do the things mentioned in this article

**Comment by bavardage** [comment]
http://bugs.java.com/view_bug.do?bug_id=JDK-6950794

edit: context here, think they should handle rotation properly when name is parameterized.
I failed at finding the actual code in the jvm where gc log rotation happens...

**Comment by schlosna** [comment]
I haven't looked at this yet, but I'd bet that many of those GC log files are from short lived invocations such as periodic health checks.

**Comment by bavardage** [comment]
yep that makes sense - I commented on the internal ticket that the pids were different each time

**Comment by uschi2000** [comment]
is this issue resolved for GJD?

**Comment by markelliot** [comment]
I think we may want to take the pid out of the GC log name in the static defaults

**Comment by schlosna** [comment]
@markelliot I don't think we want to take the PID out of the file name as your GC logs will then be blown away by the short lived process that kicked off.

**Comment by markelliot** [comment]
We could name the short lived process GC logs something different using the launcher-check.yml file to prevent that problem.

**Comment by gracew** [comment]
ok, I confirmed the short lived process IDs correspond to the processes that are spawned by checkArgs. the fix is exactly what Mark suggested, which is to put a more limited set of `jvmArgs` (if any) in the launcher-check.yml file.
