### ISSUE TITLE
Can't run my integration tests without committing

### ISSUE THREAD

**Issue by j-baker** [palantir/gradle-java-distribution#178]
A recent change enforces that versions match some sls-compliant pattern, which clearly `0.0.2-17-g2620e5c.dirty` does not. OTOH, this is for local dev work. Any chance we could revert this change? Feels broken that I can't run my tests without committing.

We have a flow where when you run a test from your IDE, it shells out to ./gradlew distTar; - this basically makes that flow useless because any investigative work needs to be accompanied by a git commit (and rebuild the world).

**Comment by uschi2000** [comment]
There's already a PR open to allow dots in the suffix. This would fix this,
right?

**Comment by uschi2000** [comment]
fixed in #176

**Comment by j-baker** [comment]
Thanks!
