### ISSUE TITLE
feature request: allow using dirty versions while debugging

### ISSUE THREAD

**Issue by ags799** [palantir/gradle-java-distribution#184]
[Release 1.4.0](https://github.com/palantir/sls-packaging/releases/tag/1.4.0) added checking for version number format, which is welcome. It has introduced a small hindrance, however, in that one cannot run `./gradlew distTar` on a dirty version. That is, you have to commit before you can `./gradlew distTar`. This can be annoying when you have to run `distTar` as part of integration tests, and you are changing code between runs of the integration tests.

Would be nice to have some way, maybe via a flag on `distTar`, to indicate that dirty versions are acceptable.

**Comment by uschi2000** [comment]
fixed in upcoming 2.0.0. can use the 2.0.0-alpha3 today.
