### ISSUE TITLE
Set version to something other than project.version

### ISSUE THREAD

**Issue by derenrich** [palantir/gradle-java-distribution#200]
Thoughts on letting users specify a version for the distribution other than the gradle project version? This would help resolve issues like the one listed in https://github.com/palantir/sls-packaging/issues/198 since you could write a regex to strip the "-dev" from the version string.

**Comment by uschi2000** [comment]
If that's desired then why not change the project version in the first place?

**Comment by derenrich** [comment]
sls-packaging has rules about versions that you might not want to reflect
in your project versions (say because you use git version).

Also, what if my project creates multiple sls-blobs but they don't all take
the same version string.

**Comment by uschi2000** [comment]
I believe it's a very practical convention that project-version == published-version, at least for anyone using sls-packaging. Different (sub-)projects can have different versions.

**Comment by derenrich** [comment]
I think it's a useful escape hatch. Also I think it's conventional for gradle plugins to let people override this.

**Comment by markelliot** [comment]
You can narrowly override project.version on a subproject basis, and we feel that is enough of an escape hatch.
