### ISSUE TITLE
gradle 3.4 java-library support using runtimeClasspath

### ISSUE THREAD

**Issue by jmcampanini** [palantir/gradle-java-distribution#201]
> When resolving the runtime classpath for Java applications, Gradle will now use the runtimeClasspath configuration instead of the runtime configuration. If you previously attached resolution rules to runtime, you should apply them to runtimeClasspath instead or apply them to all configurations.

in Gradle 3.4 ([release notes][1]), they've moved to using the `runtimeClasspath` as the configuration rather than `runtime`. i believe this means enhancing this [bit of code][2] in the `DistTarTask` to include the `runtimeClasspath`.

i believe you can check if the configuration exists by name and then add it conditionally, which should let it work with pas versions of gradle.

would a PR for this make sense?

[1]: https://docs.gradle.org/3.4/release-notes.html#runtimeclasspath-used-instead-of-runtime
[2]: https://github.com/palantir/sls-packaging/blob/develop/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/DistTarTask.groovy#L61-L64

**Comment by uschi2000** [comment]
according to https://docs.gradle.org/3.4/userguide/java_library_plugin.html#sec:java_library_configurations_graph , runtimeClasspath is internal? I don't quite understand, need to dig more.

**Comment by jmcampanini** [comment]
yea, that label of internal seems wrong, given the 2nd paragraph of the release notes:

> Tooling providers should try not to depend on configurations directly, but use sourceSet.runtimeClasspath where applicable. This always contains the correct classpath for the current Gradle version and has been changed to return the runtimeClasspath configuration in this release. If you are directly resolving the runtime configuration, your tool will not work with the java-library plugin.

**Comment by jmcampanini** [comment]
in the [gradle blog post][1] about the release:

> #### More uses cases, more configurations
> You might be aware of the `compileOnly` configuration that was introduced in Gradle 2.12, which can be used to declare dependencies which are only required when compiling a component, but not at runtime (a typical use case is libraries which are embedded into a fat jar or shadowed). The `java-library` plugin provides a smooth migration path from the `java` plugin: if you are building an application, you can continue to use the `java` plugin. Otherwise, if it’s a library, just use the `java-library` plugin. But in both cases:
> 
> * instead of the `compile` configuration, you should use `implementation` instead
> * instead of the `runtime` configuration, you should use `runtimeOnly` configuration to declare dependencies which should only be visible at runtime
> * to resolve the runtime of a component, use `runtimeClasspath` instead of `runtime`.


[1]: https://blog.gradle.org/incremental-compiler-avoidance

**Comment by jmcampanini** [comment]
there are 2 more places where the `runtime` configuration is being used that still need to be updated:

* [`CreateStartScriptsTask`][1]
* [`JavaServiceDistributionPlugin`][2]

[1]: https://github.com/palantir/sls-packaging/blob/develop/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/CreateStartScriptsTask.groovy#L31
[2]: https://github.com/palantir/sls-packaging/blob/develop/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/JavaServiceDistributionPlugin.groovy#L67

can we re-open this?
