### ISSUE TITLE
What is SLS?

### ISSUE THREAD

**Issue by nickcharles** [palantir/gradle-java-distribution#232]
Anybody?

**Comment by bjlaub** [comment]
> A set of Gradle plugins that facilitate packaging projects for distributions conforming to Palantir's Service Layout Specification. This project was formerly known as gradle-java-distribution.

Service Layout Specification. Duh.

**Comment by jared2501** [comment]
https://www.youtube.com/watch?v=Kh0Y2hVe_bw
