### ISSUE TITLE
[docs] explain productDependency properties

### ISSUE THREAD

**Issue by thasner** [palantir/gradle-java-distribution#238]
specifically, what should the `recommendedVersion` be?
See https://github.palantir.build/foundry/autopilot/pull/296#discussion_r280281

CC @leeavital

**Comment by markelliot** [comment]
minVersion = minimal compatible
maxVersion = maximal compatible
recommended = the version devs think you should use; most commonly the version of the _implementation_ that was tested during CI (minimal compatible typically matches the version of the _api_ you use to negotiate)

**Comment by markelliot** [comment]
this is spec'd in the actual spec, internally

**Comment by thasner** [comment]
> this is spec'd in the actual spec, internally

what does that mean?

I'd like to update https://github.com/palantir/sls-packaging#java-service-distribution-plugin :
> (optional) `productDependency` adds an entry to the `extensions.product-dependencies` block of the SLS manifest, declaring that this service has a dependency on the given other service with specific version bounds.

Should I link elsewhere? Or add the info you've provided inline?

**Comment by markelliot** [comment]
You can add info I wrote inline, will Slack you a link to the real docs.

On Aug 10, 2017, at 13:29, Thomas Hasner <notifications@github.com<mailto:notifications@github.com>> wrote:


this is spec'd in the actual spec, internally

what does that mean?

I'd like to update https://github.com/palantir/sls-packaging#java-service-distribution-plugin[github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_palantir_sls-2Dpackaging-23java-2Dservice-2Ddistribution-2Dplugin&d=DwMFaQ&c=izlc9mHr637UR4lpLEZLFFS3Vn2UXBrZ4tFb6oOnmz8&r=Vp81aOxWZvuVgVK_wp-VF3pIYG92B19LcCw6XKeYC0U&m=QL7Mx_eQxQEYABhUD2P_lKo6VmmmrVUYrD7iZzpDcRM&s=gXTeR6zvlugI7wAj9dL7UGO9mU3XNurCwf_NDce7QHU&e=> :

(optional) productDependency adds an entry to the extensions.product-dependencies block of the SLS manifest, declaring that this service has a dependency on the given other service with specific version bounds.

Should I link elsewhere? Or add the info you've provided inline?
