### ISSUE TITLE
`distTar` creates tarball with multiple `manifest.yaml` entries if it exists in deployment/

### ISSUE THREAD

**Issue by jonsyu1** [palantir/gradle-java-distribution#28]
This can be handled by excluding `manifest.yaml` when in the `from("${project.projectDir}/deployment") {` closure.

**Comment by jonsyu1** [comment]
@spencer-rivette @dtolnay

**Comment by markelliot** [comment]
What version are you on? I'm pretty sure this has already been fixed.

**Comment by jonsyu1** [comment]
0.3.2

**Comment by markelliot** [comment]
What do you mean by multiple manifest.yaml entries?

**Comment by jonsyu1** [comment]
When we walk the tar, we see two entries for `deployment/manifest.yaml`. Vim misbehaves and displays the two entries as copies of the concatenated files. Go's `TarReader` sees two distinct headers with the same name.

**Comment by markelliot** [comment]
Why does this matter?

The produced manifest.yaml file is deterministic.

**Comment by markelliot** [comment]
@jonsyu1 all good?

**Comment by jonsyu1** [comment]
Sorry, lost track of this issue. We resolved things on our end, so we're good to close this out.
