### ISSUE TITLE
Allow building tar with configurations other than runtime

### ISSUE THREAD

**Issue by dev-kpyc** [palantir/gradle-java-distribution#31]
My project has multiple configurations (that extend from the runtime configuration) that allow the project to be built with differently versioned jars. I would like to be able to use distTar to build a tgz for each of these configurations, but currently, the plugin only works for runtime. Currently I have a project-distribution subproject that iterates over these configurations and exposes a dist task for each (distA, distB.. etc). If I could specify which configuration to use with this plugin, then I could instead make sub-projects for each of the different configurations and apply the plugin to a different configuration on each one (project-distribution-a:distTar, project-distribution-b:distTar). That's somewhat more overhead but it's the only way that I can think of that would make this work.

**Comment by markelliot** [comment]
Any chance you could provide a minimal example project with full Gradle configs (perhaps as a sample github repo?)

I'm not totally sure I understand how you multiplex the versions.

**Comment by markelliot** [comment]
per offline discussion, @punya set up a sample project here with a proposed usage: https://github.com/punya/trilobite

I could imagine we might tweak some things or provide convenience methods to better enable, but I think his setup is reasonable for this.

**Comment by markelliot** [comment]
@dev-kpyc all set here?

**Comment by bmoylan** [comment]
I think what @punya is doing with trilobyte is the right idea. Rather than use distinct configurations within a single project, dynamically create distinct projects (you can do this within a higher build.gradle without needing checked-in directories & build files for each distribution).

**Comment by markelliot** [comment]
Closing this out.
