### ISSUE TITLE
Supporting packaged JREs?

### ISSUE THREAD

**Issue by bmoylan** [palantir/gradle-java-distribution#32]
Some products like to package a JRE to reduce their dependency on the environment. There is currently not a good way to set `JAVA_HOME` to point at the packaged one from within `init.sh` or the start scripts. I'm not totally convinced products should do this as it makes your distro larger and platform-specific (generally linux only), but it seems to be a thing people want to do. There would need to be a good way for users to override it too, unless the answer is to publish two versions of everything.

**Comment by markelliot** [comment]
I'm generally of the opinion that packaging a JRE is best done as a Docker container, which you can do easily with the gradle-docker plugin.

**Comment by bmoylan** [comment]
Sounds good to me
