### ISSUE TITLE
ignoredProductDependency should support initialization from closure

### ISSUE THREAD

**Issue by delta003** [palantir/gradle-java-distribution#351]
https://github.com/palantir/sls-packaging/blob/develop/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/BaseDistributionExtension.groovy#L125

And probably all other initialization as productDependency

**Comment by pkoenig10** [comment]
@iamdanfox @dansanduleac I would love to get this in as part of the 3.x release.
