### ISSUE TITLE
automatic gc logging lost in 2.20.0

### ISSUE THREAD

**Issue by sjrand** [palantir/gradle-java-distribution#373]
## What happened?

After I upgraded sls-packaging from 2.19.0, my service stopped writing GC logs to disk. I checked the java options on the process and I had these ones in 2.19.0, but they're gone in 2.20.0: https://github.com/palantir/sls-packaging/blob/83d78d6b6a4eee18af7d90ba010413d916883f4f/gradle-sls-packaging/src/main/groovy/com/palantir/gradle/dist/service/tasks/LaunchConfigTask.groovy#L36.

It looks like this happened as part of https://github.com/palantir/sls-packaging/pull/338.

I can see in the readme that it's possible for me to set `addJava8GCLogging` to `true` to get these back. However, I didn't have to set this explicitly before, so this is a change to the default behavior.

I'm not particularly opposed to the change in behavior, but it's not mentioned in the release notes, which makes me suspect that it may have been accidental.

## What did you want to happen?

If this was intentional, then we should mention it in the 2.20.0 release notes; if it wasn't, we should restore the previous behavior.

**Comment by iamdanfox** [comment]
@sjrand I think this change was intentional because those gc options are not compatible with Java11.

```
    private static final List<String> java8gcLoggingOptions = [
            "-XX:+PrintGCDateStamps",
            "-XX:+PrintGCDetails",
            "-XX:-TraceClassUnloading",
            "-XX:+UseGCLogFileRotation",
            "-XX:GCLogFileSize=10M",
            "-XX:NumberOfGCLogFiles=10",
            "-Xloggc:var/log/gc-%t-%p.log",
            "-verbose:gc"
    ]
```

These are mentioned in the README but I'll update the release notes for [2.20.0 too](https://github.com/palantir/sls-packaging/releases/tag/2.20.0).

**Comment by sjrand** [comment]
Okay cool, closing then
