### ISSUE TITLE
Conflicting product dependency versions aren't detected

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/gradle-java-distribution#376]
## What happened?

Consider two projects A and B, where A depends on B (or an artifact of B).
B has an explicit product dependency on product C, minimum version 0.100.0 and maximum 0.x.x.
A has an explicit product dependency on product C, minimum version 0.1.0 and maximum 0.x.x.
The manifest of a distribution of A has a product dependency on C, with minimum version 0.1.0 and maximum 0.x.x, but this is undesirable since B may be talking to APIs that don't exist in 0.1.0.

See internal object-metadata service PR 1155 for an example. In this example, C is the AtlasDB timelock server, which used to be declared only by the product (A) at 0.16.0, but then was added to atlasdb-config (B) at 0.51.0.

## What did you want to happen?

Ideally, I think dependency resolution should fail. One valid solution could be running compatibility checks and picking the intersection if one exists (here, a minimum of 0.100.0 and maximum of 0.x.x), but I think it's better to explicitly surface any such conflicts to the user.

@diogoholanda for SA

**Comment by ferozco** [comment]
Spoke offline, seems like we were not detecting constraints for the product dependency in question. Hence, the explicit product dependency in configuration was used instead of the product dependency declared by the dependency jar
