### ISSUE TITLE
manifest.yml is executable?

### ISSUE THREAD

**Issue by bmoylan** [palantir/gradle-java-distribution#48]
`manifest.yml` is set to executable. Is there a reason for this line? https://github.com/palantir/gradle-java-distribution/blob/develop/src/main/groovy/com/palantir/gradle/javadist/JavaDistributionPlugin.groovy#L95

**Comment by markelliot** [comment]
looks like a copy-paste error at some point.

**Comment by bmoylan** [comment]
Will have a PR up in a sec. Don't think it needs its own release.
