### ISSUE TITLE
Stop command should kill whole process group

### ISSUE THREAD

**Issue by punya** [palantir/gradle-java-distribution#50]
If the top-level (daemonized) service starts one or more long-running child processes, it has to ensure that those child processes get killed when the parent process is killed. This is somewhat painful to do in Java because it involves setting a shutdown hook, and it's repetitive work that's easy to get wrong. If done incorrectly, the child processes become zombies and have to be reaped manually by other means; they could take up system resources such as memory and ports.

Instead, if `init.sh` were to record the process group ID and `kill` the process group, we'd have a clean solution that works without additional work from the app.

Tagging @mingyukim, @tomkozlowski and @gdearment for comments.

**Comment by mingyukim** [comment]
+1!

**Comment by pjwalmsley** [comment]
+1

**Comment by tomkozlowski** [comment]
We should be sure to carefully test our implementation of this. I tried messing around with killing process groups in an init script earlier today and ended up accidentally killing deployd; so we should be sure we only kill processes spawned by the init script, not ones up the tree

On Jun 16, 2016, at 16:06, Patrick Walmsley <notifications@github.com<mailto:notifications@github.com>> wrote:

+1

**Comment by punya** [comment]
Stale.

**Comment by uschi2000** [comment]
@punya! Hope you're doing well :)
