### ISSUE TITLE
Avoid using afterEvaluate { } to configure the distTar task

### ISSUE THREAD

**Issue by henryptung** [palantir/gradle-java-distribution#52]
Some Gradle plugins depend, for example, on the `distTar` task output filename to resolve against artifacts or publish locations. (For example, pt-almanac.) Since `gradle-java-distribution` adds an `afterEvaluate` to configure the output name, any output filenames fetched during normal project evaluation are not reliable, and will cause those plugins to break in non-obvious ways at runtime (see HIGHLINE-1091).

The workaround, as it exists currently, is to move the publication resolution strategy (or the entire `almanacPublish` task) to an `afterEvaluate`, but I find this difficult to maintain for the same reason `_.defer` isn't desirable in JS code. If, for example, the Almanac task is placed in a shared Gradle script, depending on it or modifying its configuration would probably require a _nested_ `afterEvaluate` block.

I'd suggest refactoring the extension instead to mutate variables/properties synchronously, so that after the extension is reconfigured, the project is in a consistent/complete state and ready for further configuration. As an even stronger notion, the extension can be a call-me-once method, such that all necessary configuration is collected from the closure, and the run/dist tasks are created in immutable-state fashion from the one-time configuration closure.

**Comment by markelliot** [comment]
Things used to work that way, but because of other ordering issues, and because the plugin doesn't receive state purely through injection, I'm reasonably sure we can't accommodate this.

**Comment by markelliot** [comment]
Also, we can probably point you to several examples where you do not need to put your artifactoryPublish block into an afterEvaluate call, ping me directly for those.

**Comment by henryptung** [comment]
Sorry, not really sure I understand the context of the other ordering issues/non-injected state you're speaking of, but let me try to prototype what I'm talking about and submit a PR.

Other examples along these lines would also be helpful (in particular, ones where the project name and the archive name differ, e.g. project `raygun-server`, application name `raygun`).

**Comment by markelliot** [comment]
Fixed in 0.5.1.
