### ISSUE TITLE
productDependencies configuration might be broken with $project versions

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-java-distribution#527]
## What happened?

Using sls-packaging 3.7.5 and upgrading gradle-docker 0.21.0 -> 0.22.1, an internal project started failing with the following:

```
* What went wrong:
Execution failed for task ':lang-java-template-asset:resolveConfigurations'.
> Could not resolve all files for configuration ':lang-java-template-asset:docker'.
   > Could not find com.palantir.t.java:lang-java-asset-bundle-mega:1.97.0-18-gbdf74d8.
     Searched in the following locations:
```

Interestingly, this was the only project that had a `$projectVersion` inter-project dependency.

```
# Run ./gradlew --write-locks to regenerate this file
com.palantir.s.m:s-module-m (3.40.0, 3.x.x)
com.palantir.t.java:lang-java-asset-bundle-mega ($projectVersion, 1.x.x)
com.palantir.t.java:lang-java-s-module-asset (1.96.0, 1.x.x)
```

The `generateDockerCompose` task also failed, with the same error.

Workaround was to exclude this specific module from the `docker` configuration, as the templating functionality was never actually used!

```gradle
configurations.productDependencies {
    exclude module: 'lang-java-asset-bundle-mega'
}
```

## What did you want to happen?

`$projectVersion` should not fail to resolve, but be propagated nicely into the resultant docker-compose.yml.

**Comment by bkrieger** [comment]
We also see this in another internal repo, but the workaround is way more difficult because there are tens of dependencies to exclude.
