### ISSUE TITLE
Ability to create dist from configurations other than just `runtime`?

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-java-distribution#53]
At the moment, the `distTar` task always uses the `runtime` configuration: https://github.com/palantir/gradle-java-distribution/blob/b5d2c60a3e9e59fa382a793c834eaf8dd23b5e54/src/main/groovy/com/palantir/gradle/javadist/DistTarTask.groovy#L48

To facilitate testing plugin points, I've added an extra `eteDrivers` configuration which has a couple of extra drivers.  It would be great if the gradle-java-distribution plugin would allow me to set up both a normal `distTar` task and also an `eteDistTar` task.

**Comment by iamdanfox** [comment]
For now, the workaround I'm using is as follows.

``` groovy
    task eteDistTar(type: Tar) {
        dependsOn tasks.getByName('distTar')
        ext.distPath = tasks.getByName('distTar').outputs.files.singleFile
        from (tarTree(distPath))
        from(project.configurations.eteDrivers) {
             into(distPath.name - ".tgz" + "/service/drivers")
        }
        baseName "myproject-ete"
    }
```

**Comment by markelliot** [comment]
I think an alternative here is a virtual project like the one shown in punya/trilobite.

**Comment by markelliot** [comment]
Closing this as a dup of #31, but we'll probably add something to allow you to package additional stuff into service by enabling some additional copy specs
