### ISSUE TITLE
Fail fast when using an incompatible Java version

### ISSUE THREAD

**Issue by punya** [palantir/gradle-java-distribution#54]
Consumers should be able to specify that they want a certain major version of Java. If run with a lower version, the service script should die with an informative message (rather than falling through to Java, which will usually produce a mysterious "incompatible class format 52" message down the line).

**Comment by uschi2000** [comment]
Any suggestions how to do that?

**Comment by markelliot** [comment]
go-launcher knows a JRE to use, it could ask that JRE for the version and compare major versions. 

Not sure we need to solve this, though.

**Comment by uschi2000** [comment]
Agree, it's low priority. Closing for now.
