### ISSUE TITLE
Incorrect default variable name in config.sh

### ISSUE THREAD

**Issue by vipshek** [palantir/gradle-java-distribution#66]
Currently [this line](https://github.com/palantir/gradle-java-distribution/blob/develop/src/main/resources/config.sh#L5) mentions setting Java options using the `JVM_OPTS` environment variable, but the artifacts built using the plugin look for a variable named `JAVA_OPTS` (see [this line](https://github.com/palantir/gradle-java-distribution/blob/623cf9dc5753eced09a2c0f488035f9d33255324/gradlew#L161)).

**Comment by markelliot** [comment]
OBE due to changes in #85.
