### ISSUE TITLE
Move config.sh to var

### ISSUE THREAD

**Issue by rimig** [palantir/gradle-java-distribution#68]
Can we move config.sh to var? It seems like a better place for deployment specific configurations to stay consistent. If it's cool I can look at making a PR.

**Comment by rimig** [comment]
That's probably a @markelliot question

**Comment by markelliot** [comment]
I'd prefer not to. It's meant to be a static generated immutable file in SLS deploys, and in unmanaged cases the mutability is available to users in bin, so it shouldn't matter. 

I prefer this setup over putting a script in var (which should really be reserved for config). As an alternative we can have bash parse a config file (rather than a script) from var, but my bash foo isn't strong enough to make that work.

**Comment by mnazbro** [comment]
How is this file not configuration? After all it is called `config.sh`. The `config.sh` is the perfect place to allow a user to set service-level environment variables (which are in fact a type of configuration)

**Comment by markelliot** [comment]
It's executed as a script, not parsed as a config file, even if it contains "variables" it's nonetheless a script. Further, when deployed in SLS setups it really should be immutable and fully managed.

**Comment by mnazbro** [comment]
So, you are making the distinction that configuration does not execute arbitrary code even though the only purpose of the `config.sh` is to configure the `init.sh` script. If that's the case, it feels like an actual configuration file should be made a priority.

**Comment by sixinli** [comment]
+1 it would be nice to have a configuration file that lives in var so that it wont get replaced on every updated, modifying init.sh and config.sh requires the same amount of effort now on every update

**Comment by markelliot** [comment]
Could you describe the configuration you're trying to add and the standard kinds of edits you expect your users to make to that configuration?

**Comment by sixinli** [comment]
jvm options for example?

**Comment by rimig** [comment]
For me it is JVM args. Usually heap settings and once for yourkit.

**Comment by markelliot** [comment]
In managed environments, the manager is setting these arguments as environment variables. 

In unmanaged environments, the files aren't overwritten (by definition).

Where does the workflow issue show up?

**Comment by sixinli** [comment]
In managed environments, the manager is setting these arguments as environment variables. => on every upgrade 

the manager only want to set it once?

**Comment by markelliot** [comment]
Why would it need to be changed during an upgrade in a managed environment? In particular, I wouldn't expect humans or computers to touch config.sh in a managed environment -- our environment manager keeps and sets environment variables through upgrades. 

This file is provided so humans can edit it in unmanaged environments. 

I'm open to alternatives which do not involve executing user provided code as part of the startup process, could you propose such an alternative? (Per earlier: parsing config files using bash proved to be non-trivial.)

**Comment by markelliot** [comment]
Moving this file to var poses a security threat, so closing this as won't fix.
