### ISSUE TITLE
Allow for adding arbitrary locations to CLASSPATH

### ISSUE THREAD

**Issue by tpetracca** [palantir/gradle-java-distribution#76]
Or just var/conf?  My use case is that I need my $SERVICE_HOME/var/conf/logback.xml to exist on the classpath in order for logback to pick it up properly.

**Comment by tpetracca** [comment]
Relevant conversation with @bavardage 

[4:17 PM] 
Tom Petracca I want to add my $SERVICE_HOME/var/conf folder to my classpath

[4:17 PM] 
so java can find my logback.xml

[4:17 PM] 
Ben Duffield no good way to do that right now

[4:17 PM] 
uhm

[4:17 PM] 
was some discussion, may have been in person, about that for some hadoop stuff we need to do too

[4:18 PM] 
wondering if we shove vars which are like CP_START, CP_END

[4:18 PM] 
which we tack on start and end of cp

[4:18 PM] 
oh, but you might be able to do it in straight up gradle

[4:18 PM] 
one sec

[4:19 PM] 
Tom Petracca I was wondering if I tack on like ext.additionalClasspath to the getClasspath() method https://github.com/palantir/gradle-java-distribution/blob/develop/src/main/groovy/com/palantir/gradle/javadist/DistributionCreateStartScriptsTask.groovy

[4:19 PM] 
Ben Duffield http://stackoverflow.com/questions/30491345/how-do-i-specify-an-extra-folder-to-be-on-the-classpath-for-gradles-application
 stackoverflow.com
How do I specify an extra folder to be on the classpath for gradle's application pluin 'run' task?
I've successfully configured my gradle build script to create a zip distribution of my application with an extra 'config' folder at the root. This folder contains (at least right now) only one prop... 

[4:19 PM] 
also yeah, what you just said doesn’t seem absurd

[4:19 PM] 
but like, we should probably support adding things both at beginning and end

[4:19 PM] 
but the other way in would be in raw gradle just modify the project.configurations.runtime

[4:20 PM] 
but sorta hacky

[4:20 PM] 
Tom Petracca yea I think I want to do it the

[4:20 PM] 

```
run {
classpath += <thing>
}
```

[4:21 PM] 
I tried the runtime files() in my dependecies but it wants it to be added to libs and technically this thing won’t render until skylab makes it a thing

[4:21 PM] 
Ben Duffield ohhhh yeah good point

[4:21 PM] 
ok so probably means changing the dist plugin

[4:23 PM] 
Tom Petracca oh I can’t do the run thing b/c the plugin extends the java application plugin

**Comment by tpetracca** [comment]
While I imagine this would still be useful in other contexts, I found a way around this problem via logback's jvm property -Dlogback.configurationFile so I'm unblocked.

**Comment by sjrand** [comment]
+1

This came up today in the context of Hadoop configurations for a Hadoop client application, which wasn't using the Hadoop configurations specified in the `sparkConnection` block of its config. A fix would've been to add `core-site.xml` and `hdfs-site.xml` as provided by the client to the classpath.

**Comment by markelliot** [comment]
The classpath is built using the Gradle defined classpath; products wishing to add items to the classpath should do so at build time.

**Comment by markelliot** [comment]
ie it's not hacky, but expected that users modify `project.configurations.runtime` classpath.

**Comment by bavardage** [comment]
it's also _really hard_ to get gradle to generate a classpath which references anything outside of lib/

**Comment by markelliot** [comment]
sure, yeah, I guess we automatically copy all the things on the classpath to `lib`. Two things that I think we need to resolve:
- is it actually okay for the classpath to refer to user configured things? (this seems like a security nightmare)
- if so, what's the right way to configure those things safely?

**Comment by uschi2000** [comment]
Putting arbitrary things on the classpath == arbitrary code execution. This
is very thing we tried to prevent with the move from Gradle-generated init
scripts (which allow for bash injection attacks) to go-java-launcher.

**Comment by markelliot** [comment]
I think we could feasibly allow non-wildcard additions as long as they exist in the `service` directory (as those are, in our setups, immutable), but at that point maybe we should just say classpaths are restricted to just `service/lib`

**Comment by ash211** [comment]
@tpetracca how did you end up handling this?

The hadoop libraries expect there to be a folder on the classpath that has the `*-site.xml` config files as the main way to configure their services.  I'm unsure how to make this change using what's presently available in this gradle-java-dist and might need to make deeper product changes in this situation to make Hadoop configurable in this particular service.

cc @sjrand

**Comment by tpetracca** [comment]
I was specifically trying to figure out how to get logback's logback.xml file on the classpath.  Turns out you can work around that by explicitly setting the location of the file via a jvm argument `-Dlogback.configurationFile=<file-location>`.  So not a generic solution that will help you @ash211, sorry.

**Comment by ash211** [comment]
I'm trying to convert our sls spark history server package to use sls-packaging instead of its homegrown init scripts and am blocked on being able to add the folder `var/conf/hadoop` to the classpath.  If I add it to the list, the service is able to run.

**Comment by markelliot** [comment]
Pretty sure we do not want to allow classpath additions from the mutable part of the service deployment.

**Comment by ash211** [comment]
Not sure what you're considering mutable here -- this goes into the `launcher-static.yml` file which is not editable by service installers via configuration.  The `launcher-custom.yml` file is what administrators can configure.  This is the difference between `StaticLauncherConfig` and `CustomLauncherConfig` from https://github.com/palantir/go-java-launcher

**Comment by uschi2000** [comment]
The goal is to fix (as in, set in stone) the binary at compile time. So we have to be careful with what type of classpath additions we allow and how they interact with the mutability of the directories of the deployed application. Happy to chat more in person tomorrow.

Sent from Email+ secured by MobileIron

**Comment by ash211** [comment]
Possibly I can work around this by setting a `HADOOP_HOME` environment variable rather than the odd `var/conf/hadoop` on classpath technique which is the common practice for hadoop.

**Comment by markelliot** [comment]
We’re likely going to end up in the same place the last time someone proposed this change for Hadoop: it’s not worth adding risk to all the things for this one OSS thing, we’d prefer you accomplish this goal with something specific to Hadoop or find a way to apply the configuration that doesn’t involve the classpath.

**Comment by uschi2000** [comment]
Closing for now. Feel free to come and chat in person.
