### ISSUE TITLE
init.sh shouldn't require being run from the application root directory

### ISSUE THREAD

**Issue by spencer-rivette** [palantir/gradle-java-distribution#9]
e.g. I should be able to run /opt/some/directories/<application>/service/bin/init.sh rather than having to cd into /opt/some/directories/<application> and then service/bin/init.sh

**Comment by markelliot** [comment]
Are you sure this is an actual issue? I'm quite sure this should already work.

**Comment by spencer-rivette** [comment]
yes, this is still an issue

Here is "status"
[palantir@il-pg-alpha-47090 ~]$ /opt/palantir/gatekeeper/service/bin/init.sh status
Checking 'gatekeeper'...                          Service not running
[palantir@il-pg-alpha-47090 ~]$ cd /opt/palantir/gatekeeper/
[palantir@il-pg-alpha-47090 gatekeeper]$ ./service/bin/init.sh status
Checking 'gatekeeper'...                          Running


Here is "start"
[palantir@il-pg-alpha-47090 ~]$ /opt/palantir/gatekeeper/service/bin/init.sh start
Running 'gatekeeper'...                           Fail
[palantir@il-pg-alpha-47090 ~]$ cd /opt/palantir/gatekeeper
[palantir@il-pg-alpha-47090 gatekeeper]$ ./service/bin/init.sh start
Running 'gatekeeper'...                           Ok


Here is "stop"
[palantir@il-pg-alpha-47090 ~]$ jps
7026 Jps
6756 GatekeeperServer
[palantir@il-pg-alpha-47090 ~]$ /opt/palantir/gatekeeper/service/bin/init.sh stop
Stopping 'gatekeeper'...                          Not running
[palantir@il-pg-alpha-47090 ~]$ cd /opt/palantir/gatekeeper
[palantir@il-pg-alpha-47090 gatekeeper]$ ./service/bin/init.sh stop
Stopping 'gatekeeper'...                          Ok
[palantir@il-pg-alpha-47090 gatekeeper]$ jps
7198 Jps
[palantir@il-pg-alpha-47090 gatekeeper]$

**Comment by markelliot** [comment]
Could you attach the generated init.sh here?

**Comment by spencer-rivette** [comment]
Cheerfully:


#!/bin/bash

JAVA_HOME=/opt/palantir/jdk8

ACTION=$1
SERVICE=gatekeeper
CONFIG_FILE=var/conf/service.yml
PIDFILE="var/run/$SERVICE.pid"

if [ -n "$SERVICE_HOME" ]; then
    cd "$SERVICE_HOME"
fi

case $ACTION in
start)
    $0 status > /dev/null 2>&1
    if [[ $? == 0 ]]; then
        echo "Process is already running"
        exit 1
    fi
    printf "%-50s" "Running '$SERVICE'..."
    mkdir -p 'var/run' #ensure pid directory exists
    PID=$(service/bin/$SERVICE server $CONFIG_FILE > startup.log 2>&1 & echo $!)
    sleep 1
    if [[ $(ps $PID > /dev/null; echo $?) -eq 0 ]]; then
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
        exit 0
    else
        printf "%s\n" "Fail"
        exit 1
    fi
;;
status)
    printf "%-50s" "Checking '$SERVICE'..."
    if [ -f $PIDFILE ]; then
        PID=$(cat $PIDFILE)
        if [[ $(ps $PID > /dev/null; echo $?) -eq 0 ]]; then
            ps -o command $PID | grep -q "$SERVICE"
            if [[ $? == 0 ]]; then
                printf "%s\n" "Running"
                exit 0
            fi
        fi
        printf "%s\n" "Process dead but pidfile exists"
        exit 1
    else
        printf "%s\n" "Service not running"
        exit 3
    fi
;;
stop)
    printf "%-50s" "Stopping '$SERVICE'..."
    $0 status > /dev/null 2>&1
    if [[ $? == 0 ]]; then
        PID=$(cat $PIDFILE)
        kill $PID
        sleep 4
        $0 status > /dev/null 2>&1
        if [[ $? == 0 ]]; then
            printf "%s\n" "Failed"
            exit 1
        else
            rm -f $PIDFILE
            printf "%s\n" "Ok"
            exit 0
        fi
    else
        rm -f $PIDFILE
        printf "%s\n" "Not running"
        exit 0
    fi
;;
*)
    echo "Usage: $0 {status|start|stop}"
    exit 1
esac

**Comment by markelliot** [comment]
It looks like something is wrong with your build, as this init.sh doesn't line up with the one this plugin produces.

**Comment by markelliot** [comment]
As a reference point, here's the template for 01.1: https://github.com/palantir/gradle-java-distribution/blob/dd45023f6f1583c1c10e8583dc5596178291cfc0/src/main/resources/init.sh

**Comment by spencer-rivette** [comment]
Ok, I'll build again to make sure I'm running with the latest.

**Comment by spencer-rivette** [comment]
looks like a crufty init.sh - resolved.
