### ISSUE TITLE
add an sls configuration + artifact to the project

### ISSUE THREAD

**Issue by jmcampanini** [palantir/gradle-java-distribution#92]
// + @markelliot + @bmoylan for SA + thoughts

i'd like to refer to projects that produce a java distribution tarball via Gradle dependencies. specifically, i'd like to do something like this:

``` groovy
dependencies {
    skylab project(path: ':product', configuration: 'sls')
}
```

this would give a clean way for a project to depend on the resulting `sls` artifact produced by this plugin.

it would involve adding something like this to the plugin:

``` groovy
configurations {
    sls
}

artifacts {
    sls distTar
}
```

i believe this would be non-disruptive to existing projects.

**Comment by markelliot** [comment]
I suspect the artifacts should be resolvable even without pom files, so not sure this is necessary.

**Comment by jmcampanini** [comment]
i just tried adding the block to a simple project that has the java-distribution plugin and published to mavenLocal. i didn't see any effect on the POM file (POM for the `-server` project is below).

i was under the impression that you'd have to modify the `publishing.publications` block to modify the POM, but maybe i'm missing something.

// + @uschi2000

do you know of a different way to accomplish inter-project dependencies without the use of a configuration/artifact?

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.palantir.highlinedev</groupId>
  <artifactId>highline-dev-server</artifactId>
  <version>v1.5.0-3-g69c3b87.dirty</version>
  <packaging>tgz</packaging>
</project>
```

**Comment by uschi2000** [comment]
can you depend on the files directly? something like this (untested):

```
dependencies {
  skylab files(project(":otherProject").tasks.distTar.<need to assemble file path here))
}
```

**Comment by bmoylan** [comment]
just depending on the file doesn't add the task dependency on `distTar` for tasks which depend on the `skylab` configuration

**Comment by uschi2000** [comment]
That's correct.

**Comment by jmcampanini** [comment]
the goal is to have the dependency trigger the creation of the tarball.

**Comment by markelliot** [comment]
Why isn't that something your plugin is configuring, though?

**Comment by jmcampanini** [comment]
the scenario this is trying to solve is a multi-project setup:
1. there are multiple services in a single repository (compass + compass-blobster)
2. an `-ete` project is depending on the `-server` project

so the kennedy plugin isn't directly applied to the server plugin, but the `java-distribution` plugin is. we could technically make a `kennedy-artifact` or some sort of `sls-artifact` plugin, but it seems that it would explicitly only be used with this plugin. and since this plugin makes sls-compliant artifacts, the thought was to expose that fact as a particular configuration+artifact in gradle-land.

**Comment by markelliot** [comment]
Yep, sure, so the dependencies could be something like:

dependencies {
    foo project(':other-project').distTar
}

Or, the plugin that you're applying can add this custom configuration stuff. Not clear to me why the distribution plugin should need to add this configuration.

**Comment by jmcampanini** [comment]
> Yep, sure, so the dependencies could be something like:

that only works if you force the evaluation of other project:

``` groovy
evaluationDependsOn(':other-project')
```

this is more fragile than necessary, and is something that is directly addressed via artifacts + inter-project dependencies.

> Or, the plugin that you're applying can add this custom configuration stuff

is it good practice for a plugin to affect OTHER project's configuration? that to me seems a bit dangerous, but if it's common gradle practice, that would work.

---

in general, this plugin does add a new artifact to the project - the distributable tarball made by `:distTar`. exposing it via gradle's common mechanisms could be useful to other people.

since there is a workaround for the scenario i'm running into (explicitly adding the config + artifact or the project evaluate), it's not pressing. but it would be nice to see this plugin start to use the common gradle practices for sharing artifacts.

**Comment by markelliot** [comment]
Why does registering the distTar artifact require adding a new configuration type?

**Comment by markelliot** [comment]
(sorry, I think maybe I'm just not that familiar with this part of the Gradle toolchain)

**Comment by jmcampanini** [comment]
np. very open to finding a better way of doing this.

from the searching/reading i've done, this seems to be the simplest/complete approach. an example of this being used can be found on [Gradle Goodness](http://mrhaki.blogspot.com/2016/02/gradle-goodness-inter-project-artifact.html) and in the [gradle docs](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:artifacts%28groovy.lang.Closure%29).

from my understanding ([docs](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.Configuration.html)), configurations are used to share a collection of files/artifacts, like in inter-project java sharing a runtimeConfiguration.

there is a concept of a `default` configuration, which allows you to just write:

``` groovy
dependencies {
    compile project(':other-project')
}
```

without the `configuration:` part. i believe the java plugin ends up using this mechanism to make their syntax clean.

since there is a possibility that projects want to reference the java-related configuration of their `-server` project (the project with `java-distribution` applied, which is a java project), i'm suggesting making a different configuration, one that is only used for this 1 file.

**Comment by markelliot** [comment]
Ok, I'm fine with this I guess. Looking forward to the PR. "sls" seems like an okay config name but the readme should explain what it stands for for clarity.

**Comment by jmcampanini** [comment]
sounds good. will work on it this week.
